import type { NextPage } from "next";
import Head from "next/head";

// Styles
import styles from "../styles/Home.module.css";

// Components
import BookList from "../components/BookList";
import AuthorList from "../components/AuthorList";

const Home: NextPage = () => {
  return (
    <main className={styles.HomePage}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BookList page={2} />
      <AuthorList page={1} />
    </main>
  );
};

export default Home;
