import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

// Styles
import styles from "../styles/Home.module.css";

// Components
import HomeBookList from "../components/HomeBookList";
import AuthorList from "../components/AuthorList";

const Home: NextPage = () => {
  const [authorPage, setAuthorPage] = useState(1);
  return (
    <main className={styles.HomePage}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeBookList />
      <AuthorList
        isRow={false}
        maxAuthors={10}
        page={authorPage}
        setPage={setAuthorPage}
      />
    </main>
  );
};

export default Home;
